# Generated by Django 3.2 on 2021-06-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='img',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
