# Generated by Django 3.2 on 2021-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_team_member_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Working_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
            ],
        ),
    ]
