# Generated by Django 3.2 on 2021-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('bid_amt', models.CharField(max_length=20)),
                ('bid_by', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
