# Generated by Django 3.2 on 2021-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('sub_class', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
                ('fuel_type', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('registration_state', models.CharField(max_length=50)),
                ('driven', models.CharField(max_length=50)),
                ('number_of_owner', models.CharField(max_length=50)),
                ('condition_grade', models.CharField(max_length=50)),
                ('expected_price', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
